// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::GUEST_ELF;
use risc0_zkvm::{default_prover, ExecutorEnv};

use pallas_network::{facades::PeerClient, miniprotocols::Point};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // An executor environment describes the configurations for the zkVM
    // including program inputs.
    // A default ExecutorEnv can be created like so:
    // `let env = ExecutorEnv::builder().build().unwrap();`
    // However, this `env` does not have any inputs.
    //
    // To add guest input to the executor environment, use
    // ExecutorEnvBuilder::write().
    // To access this method, you'll need to use ExecutorEnv::builder(), which
    // creates an ExecutorEnvBuilder. When you're done adding input, call
    // ExecutorEnvBuilder::build().

    let hash = std::env::var("BLOCK_HASH").unwrap();
    let hash = hex::decode(hash).unwrap();
    let mut peer_client = PeerClient::connect("preprod-node.play.dev.cardano.org:3001", 1).await?;
    let client = peer_client.blockfetch();
    let slot = std::env::var("BLOCK_SLOT").unwrap();
    let raw_block = client.fetch_single(Point::Specific(slot.parse()?, hash)).await?;

    let env = ExecutorEnv::builder()
        .write(&raw_block)
        .unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest
    let prove_info = prover
        .prove(env, GUEST_ELF)
        .unwrap();

    // extract the receipt.
    let receipt = prove_info.receipt;

    let output: String = receipt.journal.decode().unwrap();

    println!("{}", receipt);

    Ok(())
}
